name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clear contents of /var/www/html
        run: ssh -o StrictHostKeyChecking=no nighthawk@20.42.96.235 'sudo rm -rf /var/www/html/*'

      - name: Clone repository to Azure VM
        run: ssh -o StrictHostKeyChecking=no nighthawk@20.42.96.235 'git clone https://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@github.com/nighthawknb/ento-project /var/www/html'